name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'
steps:
  - name: Git checkout
    uses: actions/checkout@v2
    with:
      fetch-depth: '0'
  - name: git
    run: |
      # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
      git --version
      git config user.name "GitHub Actions Bot"
      git config user.email "<>"
      git status
      git tag
      git describe
